server {
    listen 80;
    listen [::]:80;
    server_name urfit.io www.urfit.io;
    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
    }

    #https server configuration
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    # SSL certificates managed by Certbot
    ssl_certificate /etc/letsencrypt/live/urfit.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/urfit.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    # Server name
    server_name urfit.io www.urfit.io;
    # Reverse proxy to container (running on port 8080 o>
    location / {
    proxy_pass http://localhost:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass Upgrade $http_upgrade;
    }
}