docker run -d \
  --hostname urfitio_app \
  -p 8080:80 \
  -v /etc/letsencrypt:/etc/letsencrypt:ro \
  -e url="${url}" \
  -e api_key="${api_key}" \
  -e max_tokens="${max_tokens}" \
  -e model="${model}" \
  -e temperature="${temperature}" \
  -e database="${database}" \
  -e username="${username}" \
  -e password="${password}" \
  -e host="${host}" \
  -e port="${port}" \
  -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
  -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
  -e ALGORITHM="${ALGORITHM}" \
  -e ACCESS_TOKEN_EXPIRE="${ACCESS_TOKEN_EXPIRE}" \
  -e REFRESH_TOKEN_EXPIRE="${REFRESH_TOKEN_EXPIRE}" \
  -e SECRET_KEY="${SECRET_KEY}" \
  -e SIGNUP_TOKEN_EXPIRE="${SIGNUP_TOKEN_EXPIRE}" \
  -e source_email="${source_email}" \
  -e source_domain="${source_domain}" \
  -e SMTP_SERVER="${SMTP_SERVER}" \
  -e SMTP_PORT="${SMTP_PORT}" \
  -e SMTP_USERNAME="${SMTP_USERNAME}" \
  -e SMTP_PASSWORD="${SMTP_PASSWORD}" \
  tubaca14/urfitio
